framework.asp/Models/producto_imagen.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace framework.asp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_imagen
    {
        public int id { get; set; }
        public string imagen { get; set; }
        public int id_producto { get; set; }
    
        public virtual producto producto { get; set; }
    }
}

framework.asp/Controllers/ProductoImagenController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using framework.asp.Models;

namespace framework.asp.Controllers
{
    
    public class ProductoImagenController : Controller
    {
        [Authorize]
        // GET: ProductoImagen
        public ActionResult Index()
        {
            using (var db = new inventario2021Entities())
            {
                return View(db.producto_imagen.ToList());
            }

            
        }

        public static string NombreProducto(int idproducto)
        {
            using (var db = new inventario2021Entities())
            {
                return db.producto.Find(idproducto).nombre;
            }
        }

        public ActionResult ListarProducto()
        {
            using (var db = new inventario2021Entities())
            {
                return PartialView(db.producto.ToList());
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(producto_imagen producto_Imagen)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                using (var db = new inventario2021Entities())
                {
                    db.producto_imagen.Add(producto_Imagen);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();

            }


        }

        public ActionResult Details(int id)
        {
            using (var db = new inventario2021Entities())
            {
                return View(db.producto_imagen.Find(id));
            }
        }

        public ActionResult Edit(int id)
        {
            using (var db = new inventario2021Entities())
            {
                producto_imagen productoimagenEdit = db.producto_imagen.Where(a => a.id == id).FirstOrDefault();
                return View(productoimagenEdit);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit(producto_imagen productoimagenEdit)
        {
            try
            {
                using (var db = new inventario2021Entities())
                {
                    var productoimagen = db.producto_imagen.Find(productoimagenEdit.id);
                    productoimagen.imagen = productoimagenEdit.imagen;
                    productoimagen.id_producto = productoimagenEdit.id_producto;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }

        }

        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventario2021Entities())
                {
                    producto_imagen productoimagen = db.producto_imagen.Find(id);
                    db.producto_imagen.Remove(productoimagen);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }
        }

        public ActionResult CargarImagen()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CargarImagen(producto producto, HttpPostedFileBase imagen)
        {
            try
            {
                //string para guardar la ruta
                string filePath = string.Empty;
                string nameFile = "";

                //condicion para saber si el archivo llego
                if (imagen != null)
                {
                    //ruta de la carpeta que guardara el archivo
                    string path = Server.MapPath("~/Uploads/Imagenes/");

                    //condicion para saber si la carpeta uploads existe
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }

                    nameFile = Path.GetFileName(imagen.FileName);

                    //obtener el nombre del archivo
                    filePath = path + Path.GetFileName(imagen.FileName);

                    //obtener la extension del archivo
                    string extension = Path.GetExtension(imagen.FileName);

                    //guardar el archivo
                    imagen.SaveAs(filePath);
                }

                using (var db = new inventario2021Entities())
                {
                    var imagenProducto = new producto_imagen();
                    imagenProducto.producto = producto;
                    imagenProducto.imagen = "/Uploads/Imagenes/" + nameFile;
                    db.producto_imagen.Add(imagenProducto);
                    db.SaveChanges();

                }

                return View();

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }

        }
    }



}

framework.asp/Views/ProductoImagen/CargarImagen.cshtml
<h2>Cargar Imagen Producto</h2>

@using (Html.BeginForm("CargarImagen", "ProductoImagen", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label class="control-label col-md-2">Producto</label>
        <div class="col-md-10">
         @Html.Action("ListarProducto")
       
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Imagen</label>
        <div class="col-md-10">
            <input type="file" name="imagen" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Enviar" class="form-control" />
        </div>
    </div>
}

framework.asp/Views/ProductoImagen/Create.cshtml
@model framework.asp.Models.producto_imagen

@{
    ViewBag.Title = "Create";
}

<h2>Crear Producto Imagen</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2" for="imagen">Imagen</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.imagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="id_producto">Producto</label>
            <div class="col-md-10">
                @Html.Action("ListarProducto")
                @Html.ValidationMessageFor(model => model.id_producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>

framework.asp/Views/ProductoImagen/Details.cshtml
@model framework.asp.Models.producto_imagen

@{
    ViewBag.Title = "Details";
}

<h2>Detalles Producto Imagen</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Imagen
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imagen)
        </dd>

        <dt>
            Producto
        </dt>

        <dd>
            @framework.asp.Controllers.ProductoImagenController.NombreProducto(Model.id_producto)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Volver a la lista ", "Index")
</p>

framework.asp/Views/ProductoImagen/Edit.cshtml
@model framework.asp.Models.producto_imagen

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Producto imagen</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            <label class="control-label col-md-2" for="imagen">Imagen</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.imagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="id_producto">Producto</label>
            <div class="col-md-10">
                @Html.Action("ListarProducto")
                @Html.ValidationMessageFor(model => model.id_producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>

framework.asp/Views/ProductoImagen/Index.cshtml
@model IEnumerable<framework.asp.Models.producto_imagen>

@{
    ViewBag.Title = "Index";
}

<h2>Lista Producto Imagen</h2>

<p>
    @Html.ActionLink("Crear Producto Imagen", "Create")
</p>
<table class="table table-bordered table-hover">
    <tr>
        <th>
            Imagen
        </th>
        <th>
            Producto
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.imagen)
            </td>
            <td>
                @framework.asp.Controllers.ProductoImagenController.NombreProducto(item.id_producto)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.id }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.id }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.id }, new { @class = "linkDelete" })
            </td>
        </tr>
    }

</table>

@section scripts{
    <script>
        $(".linkDelete").click(function (event) {
            if (!confirm('¿Esta seguro de eliminar?')) {
                event.preventDefault();
            }
        })
    </script>
}

framework.asp/Views/ProductoImagen/ListarProducto.cshtml
@model IEnumerable<framework.asp.Models.producto>

<select class="form-control" id="id_producto" name="id_producto">
    @foreach (var item in Model)
    {
        <option value="@item.id">@item.nombre</option>
    }
</select>